name: Test & Lint Exercises Data

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install linting dependencies
        run: make install
      - name: Lint JSON to ensure it conforms with schema
        run: make lint
      - name: Ensure dist/exercises_en.json is up to date
        run: |
          mv dist/exercises_en{,.original}.json
          make dist/exercises_en.json
          diff -q dist/exercises_en{,.original}.json
      - name: Ensure dist/exercises_pt.json is up to date
        run: |
          mv dist/exercises_pt{,.original}.json
          make dist/exercises_pt.json
          diff -q dist/exercises_pt{,.original}.json
      - name: Ensure metadata is generated and up to date
        run: make metadata
      - name: Ensure workouts are validated and hydrated
        run: make workouts
